version: '3'
services:
  vulnerable:
    # Vulnerable version of Elasticsearch allows Remote Code Execution 
    # See CVE-2015-1427 at https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-1427
    image: benhall/elasticsearch:1.4.2
    ports:
     - "9200:9200"
    networks:
      - default

  badguy:
    build: .
    tty:  true
    networks:
      - default

networks:
  default: